language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '14'
git:
  depth: 3
script:
  - yarn --cwd /platzi-store-jest-01-react-jest/ test
  - yarn --cwd /platzi-store-jest-01-react-jest/ build
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: platzi-store-jest-01-react-jest/dist/
  target-branch: gh-pages
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: master